### ISSUE TITLE
Too much space in combined view with newlines

### ISSUE THREAD

**Issue by codecat** [jfcherng/php-diff#34] opened 2020-08-08 13:42 UTC
![image](https://user-images.githubusercontent.com/136534/89711875-52bdad80-d98d-11ea-9d53-8ac1be2cabde.png)

Problem seems to be a newline between these two `<br>` tags:

![image](https://user-images.githubusercontent.com/136534/89711894-6bc65e80-d98d-11ea-99aa-fb0f8eaeed95.png)

Removing the actual newline between the two tags using Firefox's inspector solves the problem for me:

![image](https://user-images.githubusercontent.com/136534/89711929-9e705700-d98d-11ea-8af0-6664066b301f.png)

I use the following code to render the page:
```php
$diff = DiffHelper::calculate($model->OldContent, $model->NewContent, 'Combined', array(
	'context' => Differ::CONTEXT_ALL,
), array(
	'detailLevel' => 'word',
));

echo '<html><head><link rel="stylesheet" href="/vendor/jfcherng/php-diff/example/diff-table.css"></head><body>';
echo '<pre style="border:1px solid #000;">' . $model->OldContent . '</pre>';
echo '<pre style="border:1px solid #000;">' . $model->NewContent . '</pre>';
echo $diff;
echo '</body>';
```

**Comment by codecat** [comment] 2020-08-08 13:45
As a workaround, this seems to work well: `echo preg_replace('/[\n\r]/', '', $diff);`

**Comment by jfcherng** [comment] 2020-08-08 14:10
Hmmm... yeah. That looks like there is an extra empty line in the output.

**Comment by jfcherng** [comment] 2020-08-08 14:16
By the way, please provide old/new sources in plain text so people can copy-and-paste to reproduce it easily.

**Comment by codecat** [comment] 2020-08-08 14:18
You're right, I shouldn't assume that a screenshot is enough! 👍 

## Old
```
# Foo
Foo is a test term in computer science.

![](/imgu/7109e8628472fc6805ff18a744fc8a7c96a4c0e4.png)
```

## New
```
# Foo
Foo is a test word in computer science.

There is also something to be said about `bar`.

![](/imgu/7109e8628472fc6805ff18a744fc8a7c96a4c0e4.png)
```

**Comment by jfcherng** [comment] 2020-08-10 14:08
I seem not able to reproduce this on my side. Are you using the latest release?

![image](https://user-images.githubusercontent.com/6594915/89791514-0376a900-db56-11ea-9fed-e78ca2bb4c7a.png)

**Comment by codecat** [comment] 2020-08-10 14:11
Perhaps it's worth mentioning I'm using Firefox - not sure if the browser makes a difference. I can test this again in a few minutes.

**Comment by jfcherng** [comment] 2020-08-10 14:20
Tried Firefox 79 but in vain.

![image](https://user-images.githubusercontent.com/6594915/89792805-9e23b780-db57-11ea-8836-2d27ee86618f.png)

If you can create a minimal reproducer repository will be great :+1:

**Comment by jfcherng** [comment] 2020-08-10 14:21
I would still like to ensure that you are using the `6.7.4` release of `jfcherng/php-diff`.

**Comment by codecat** [comment] 2020-08-10 14:53
Yes, I'm using 6.7.4. I figured out what the problem is though! 🎉 

My input has `\r\n` newlines rather than only `\n`. Inspecting the HTML output, it seems like the `\r` is there in between those `<br>` tags!

**Comment by jfcherng** [comment] 2020-08-10 14:56
> My input has `\r\n` newlines rather than only `\n`. Inspecting the HTML output, it seems like the `\r` is there in between those `<br>` tags!

Great! I am able to reproduce it now.

**Comment by jfcherng** [comment] 2020-08-10 15:40
Should've been fixed in https://github.com/jfcherng/php-diff/commit/35a250235f4224b89b951605f079d7aa3c184f26. `6.7.5` released. It ends up to be a CSS problem.

**Closed as completed by jfcherng** 2020-08-10 15:40 UTC
Labels: bug

**Comment by codecat** [comment] 2020-08-10 16:30
Thanks for the fix! 🥰
